spring:
  application:
    name: home-inventory
  datasource:
    url: jdbc:h2:mem:home_inventory;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/home_inventory
    driver-class-name: org.postgresql.Driver
    username: home_inventory
    password: home_inventory
