spring:
  application:
    name: home-inventory
  datasource:
    url: jdbc:h2:mem:home_inventory;MODE=MariaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  servlet:
    multipart:
      max-file-size: ${HOME_INVENTORY_FILES_MAX_UPLOAD_SIZE:10MB}
      max-request-size: ${HOME_INVENTORY_FILES_MAX_UPLOAD_SIZE:10MB}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

home-inventory:
  files:
    storage-path: ${HOME_INVENTORY_FILES_STORAGE_PATH:.local/files}
    max-upload-size: ${HOME_INVENTORY_FILES_MAX_UPLOAD_SIZE:10MB}

---
spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:home_inventory}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME:home_inventory}
    password: ${DB_PASSWORD:home_inventory}
